app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, blog_index, blog_list, blog_content

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('blog_index', blog_index, name='blog_index'),
    path('blog_list/<str:catalogue>', blog_list, name='blog_list'),
    path('blog_list/blog_content/<int:num>', blog_content, name='blog_content'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from app import urls as appurls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(appurls))
]

app/models.py
from django.db import models
import django.utils.timezone as timezone


class TagInfo(models.Model):

    tag_name = models.CharField(max_length=20)

    def __str__(self):

        return self.tag_name


class BlogInfo(models.Model):

    blog_title = models.CharField(max_length=20)
    blog_content = models.TextField()
    blog_summary = models.CharField(max_length=100)
    add_date = models.DateTimeField('保存日期', default=timezone.now)
    catalogue = models.CharField(max_length=30)
    tag = models.ForeignKey(TagInfo, on_delete=models.CASCADE)

    def __str__(self):

        return self.blog_title

app/views.py
from django.shortcuts import render
from app.models import BlogInfo
import markdown
# Create your views here.


def index(request):

    return render(request, 'index.html')


def blog_index(request):

    return render(request, 'blog_index.html')


def blog_list(request, catalogue):

    blogs = BlogInfo.objects.filter(catalogue=catalogue)

    return render(request, 'blog_list.html', {'blogs': blogs})


def blog_content(request, num):

    blog = BlogInfo.objects.get(id=num)
    blog.blog_content = markdown.markdown(blog.blog_content, extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])

    return render(request, 'blog_content.html', {'blog': blog})

templates/blog_content.html
<!DOCTYPE HTML>

<html>
	<head>
		<title>BLOG_LIST</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="/static/css/main02.css" />
        <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">
        <style>
    .codehilite {
      padding: 0;
    }

    /* for block of numbers */
    .hljs-ln-numbers {
      -webkit-touch-callout: none;
      -webkit-user-select: none;
      -khtml-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;

      text-align: center;
      color: #ccc;
      border-right: 1px solid #CCC;
      vertical-align: top;
      padding-right: 5px;
    }

    .hljs-ln-n {
      width: 30px;
    }

    /* for block of code */
    .hljs-ln .hljs-ln-code {
      padding-left: 10px;
      white-space: pre;
    }
  </style>
	</head>
	<body>

		<!-- Header -->

            <header id="header">
				<a href="{% url 'app:index' %}" class="logo"><strong>BlogPages</strong> by 雨豪</a>
				<nav>
					<a href="#menu">Menu</a>
				</nav>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="{% url 'app:index' %}">首页</a></li>
					<li><a href="#">涂鸦（正在开发）</a></li>
					<li><a href="#">相册（正在开发）</a></li>
				</ul>
			</nav>

		<!-- Main -->
			<section id="main">
				<div class="inner">
					<div class="image fit">
					</div>
                    <h1>{{ blog.blog_title }}</h1>
                    <h2>{{ blog.blog_summary }}</h2>
                    <p>{{ blog.blog_content|safe }}</p>
                    <p>Migrations

Django中对Model进行修改是件麻烦的事情，syncdb命令仅仅创建数据库里还没有的表，它并不对已存在的数据表进行同步修改,也不处理数据模型的删除。 如果你新增或修改数据模型里的字段,或是删除了一个数据模型，你需要手动在数据库里进行相应的修改或者使用South。Django 1.7中已经集成了South的代码，提供了3个新命令：

migrate: 用于执行迁移动作，具有syncdb的功能
makemigrations: 基于当前的model创建新的迁移策略文件
sqlmigrate: 显示迁移的SQL语句，具有sqlall的功能
使用起来很简单，对Model做了修改后，使用makemigrations记录修改：

1
2
3
4
$ python manage.py makemigrations
Migrations for 'books':
  0003_auto.py:
    - Alter field author on book
你的Model会被扫描, 然后与migrations文件夹中以前的版本作比较, 然后生成本次迁移文件。

有了新的migration文件，就可以使用migrate修改数据库模式：

1
2
3
4
5
6
7
8
9
10
11
$ python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: sessions, admin, messages, auth, staticfiles, contenttypes
  Apply all migrations: books
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Installed 0 object(s) from 0 fixture(s)
Running migrations:
  Applying books.0003_auto... OK
也可以针对单独的app生成migration：

1
$ python manage.py makemigrations your_app_label
也可以对数据库中的数据进行修改，首先建立一个空的migration文件：

1
python manage.py makemigrations --empty yourappname
文件的内容如下：

1
2
3
4
5
6
7
8
9
10
11
# -*- coding: utf-8 -*-
from django.db import models, migrations

class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0001_initial'),
    ]

    operations = [
    ]
如果想修改某个Model例如Person的数据，设置其name字段：

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
# -*- coding: utf-8 -*-
from django.db import models, migrations

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Person = apps.get_model("yourappname", "Person")
    for person in Person.objects.all():
        person.name = "%s %s" % (person.first_name, person.last_name)
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
最后运行 python ma</p>
                <p>{{ blog.add_date }}</p>

					</div>

			</section>

		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
				    <li><a href="https://github.com/hyh1207" class="icon fa-github"><span class="label">Github</span></a></li>
					<li><a href="#" class="icon fa-wechat"><span class="label">微信</span></a></li>
					<li><a href="#" class="icon fa-qq"><span class="label">qq</span></a></li>
				</ul>

			</footer>

		<!-- Scripts -->

            <script src="/static/js/jquery.min.blog.js"></script>
			<script src="/static/js/jquery.scrolly.min.blog.js"></script>
			<script src="/static/js/skel.min.blog.js"></script>
			<script src="/static/js/util.blog.js"></script>
			<script src="/static/js/main.blog.js"></script>
            <script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
  <script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
  <script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
  </script>

	</body>
</html>

templates/blog_index.html
<!DOCTYPE HTML>



<html>
	<head>
		<title>博客</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="../static/css/main02.css" />

	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<a href="{% url 'app:index' %}" class="logo"><strong>BlogPages</strong> by 雨豪</a>
				<nav>
					<a href="#menu">Menu</a>
				</nav>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="{% url 'app:index' %}">首页</a></li>
					<li><a href="#">涂鸦（正在开发）</a></li>
					<li><a href="#">相册（正在开发）</a></li>
				</ul>
			</nav>

		<!-- Banner -->
			<section id="banner">
				<div class="inner">
					<h1>我的博客<br />
					My Blog</h1>
					<ul class="actions">
						<li><a href="#one" class="button alt scrolly big">Continue</a></li>
					</ul>
				</div>
			</section>

            {#		文本#}
			<article id="one" class="post style1">
				<div class="image">
					<img src="../static/images/image99.jpg" alt="" data-position="75% center" />
				</div>
				<div class="content">
					<div class="inner">
						<header>
							<h2>Python</h2>
                            <p>django</p>
                            <p>本网站基于 <strong>Python3.7+django2.1.2+mysql8.0.1+simpleui</strong></p>
                            <p>部署：<strong>uwsgi+nginx</strong></p>
						</header>
						<ul class="actions">
							<li><a href="blog_list/python" class="button alt">Read More</a></li>
{#                            <li><a href="#" class="button alt">Read More</a></li>#}

						</ul>
					</div>
					<div class="postnav">
                        <a href="#" class="scrolly prev"><span class="icon fa-chevron-up"></span></a>
                        <a href="#two" class="scrolly next"><span class="icon fa-chevron-down"></span></a>
					</div>
				</div>
			</article>


            <article id="two" class="post invert style1 alt">
				<div class="image">
					<img src="../static/images/img01.jpg" alt="" data-position="10% center" />
				</div>
				<div class="content">
					<div class="inner">
						<header>
							<h2>计网+计组+数据结构与算法（Python）</h2>
							<p class="info">计算机网络原理--计算机组成原理--数据结构与算法</p>
						</header>
                        <p></p>
						<ul class="actions">
							<li><a href="blog_list/basic" class="button alt">Read More</a></li>
						</ul>
					</div>
					<div class="postnav">
						<a href="#one" class="scrolly prev"><span class="icon fa-chevron-up"></span></a>
						<a href="#three" class="scrolly next"><span class="icon fa-chevron-down"></span></a>
					</div>
				</div>
			</article>
            <article id="three" class="post style2">
				<div class="image">
                    <img src="../static/images01/jeVh67AofYU.jpg" alt="" data-position="60% center" />

				</div>
				<div class="content">
					<div class="inner">
						<header>
							<h2>前端</h2>
							<p class="info">HTML+CSS+JS</p>
						</header>
                        <p></p>
                        <ul class="actions">
							<li><a href="blog_list/front" class="button alt">Read More</a></li>
						</ul>
					</div>
					<div class="postnav">
						<a href="#two" class="scrolly prev"><span class="icon fa-chevron-up"></span></a>
						<a href="#four" class="scrolly next"><span class="icon fa-chevron-down"></span></a>
					</div>
				</div>
			</article>
            <article id="four" class="post invert style2 alt">
				<div class="image">
                    <img src="../static/images01/Utsvwy1XAX4.jpg" alt="" data-position="80% center" />

				</div>
				<div class="content">
					<div class="inner">
						<header>
							<h2>数据库</h2>
							<p class="info">mysql--redis--mongodb</p>
						</header>
                        <p>这是内容</p><ul class="actions">
							<li><a href="blog_list/mysql" class="button alt">Read More</a></li>
						</ul>
					</div>
					<div class="postnav">
						<a href="#three" class="scrolly prev"><span class="icon fa-chevron-up"></span></a>
						<a href="#five" class="scrolly next"><span class="icon fa-chevron-down"></span></a>

					</div>
				</div>
			</article>
            <article id="five" class="post style3">
				<div class="image">
					<img src="../static/images01/9zH3AfW7O4o.jpg" alt="" data-position="5% center" />
				</div>
				<div class="content">
					<div class="inner">
						<header>
							<h2>GIT,Docker等常用工具</h2>
							<p class="info"><strong>GIT</strong> 是一个开源的分布式版本控制系统，可以有效、高速地处理从很小到非常大的项目版本管理。</p>
                            <p class="info"> <strong> Docker</strong> 是一个开源的应用容器引擎，让开发者可以打包他们的应用以及依赖包到一个可移植的镜像中，然后发布到任何流行的 Linux或Windows 机器上，也可以实现虚拟化。容器是完全使用沙箱机制，相互之间不会有任何接口</p>
						</header>

						<ul class="actions">
							<li><a href="blog_list/git" class="button alt">Read More</a></li>
						</ul>
					</div>
					<div class="postnav">
						<a href="#four" class="scrolly prev"><span class="icon fa-chevron-up"></span></a>
						<a href="#six" class="scrolly next"><span class="icon fa-chevron-down"></span></a>
					</div>
				</div>
			</article>

            <article id="six" class="post invert style3 alt">
				<div class="image">
					<img src="../static/images01/KWxlPUbhpH0.jpg" alt="" data-position="80% center" />
				</div>
				<div class="content">
					<div class="inner">
						<header>
							<h2>Linux</h2>
							<p class="info">centos</p>
						</header>

						<ul class="actions">
							<li><a href="blog_list/linux" class="button alt">Read More</a></li>
						</ul>
					</div>
					<div class="postnav">
						<a href="#five" class="scrolly prev"><span class="icon fa-chevron-up"></span></a>
						<a href="#" class="scrolly next disabled"><span class="icon fa-chevron-down"></span></a>
					</div>
				</div>
			</article>







		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
					<li><a href="https://github.com/hyh1207" class="icon fa-github"><span class="label">Github</span></a></li>
					<li><a href="#" class="icon fa-wechat"><span class="label">微信</span></a></li>
					<li><a href="#" class="icon fa-qq"><span class="label">qq</span></a></li>
				</ul>

			</footer>

		<!-- Scripts -->
			<script src="/static/js/jquery.min.blog.js"></script>
			<script src="/static/js/jquery.scrolly.min.blog.js"></script>
			<script src="/static/js/skel.min.blog.js"></script>
			<script src="/static/js/util.blog.js"></script>
			<script src="/static/js/main.blog.js"></script>


	</body>
</html>

templates/blog_list.html
<!DOCTYPE HTML>

<html>
	<head>
		<title>BLOG_LIST</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="../static/css/main02.css" />
	</head>
	<body>

		<!-- Header -->

            <header id="header">
				<a href="{% url 'app:index' %}" class="logo"><strong>BlogPages</strong> by 雨豪</a>
				<nav>
					<a href="#menu">Menu</a>
				</nav>
			</header>

		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="{% url 'app:index' %}">首页</a></li>
					<li><a href="#">涂鸦（正在开发）</a></li>
					<li><a href="#">相册（正在开发）</a></li>
				</ul>
			</nav>

		<!-- Main -->
			<section id="main">
				<div class="inner">
					<div class="image fit">
                        {% for blog in blogs %}
                        <ul>
                            <li><a href="blog_content/{{ blog.id }}">{{ blog.blog_title }}</a>----{{ blog.blog_summary }}---{{ blog.add_date }}</li>
                        </ul>
                        {% endfor %}
						<img src="../static/images01/-kT_jqkMmFc.jpg" alt="" />
					</div>
                </div>



			</section>

		<!-- Footer -->
			<footer id="footer">
				<ul class="icons">
				    <li><a href="https://github.com/hyh1207" class="icon fa-github"><span class="label">Github</span></a></li>
					<li><a href="#" class="icon fa-wechat"><span class="label">微信</span></a></li>
					<li><a href="#" class="icon fa-qq"><span class="label">qq</span></a></li>
				</ul>

			</footer>

		<!-- Scripts -->

            <script src="/static/js/jquery.min.blog.js"></script>
			<script src="/static/js/jquery.scrolly.min.blog.js"></script>
			<script src="/static/js/skel.min.blog.js"></script>
			<script src="/static/js/util.blog.js"></script>
			<script src="/static/js/main.blog.js"></script>

	</body>
</html>

templates/index.html


<!DOCTYPE HTML>
<html>
	<head>
		<title>首页</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="../static/css/main01.css" />
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<div class="inner">
					<a href="index.html" class="logo"><strong>YUHAOS</strong></a>
					<nav id="nav">
						<a href="index.html">Home</a>
						<a href={% url 'app:blog_index' %}>blog</a>
	
					</nav>
					<a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
				</div>
			</header>

		<!-- Banner -->
			<section id="banner">
				<div class="inner">
					<header>
						<h1>Welcome YUHAOS'SITE</h1>
                        <h2 style="color: white">大学生 全栈发展ing</h2>

					</header>

					<div class="flex ">

						<div>
							<span class="icon fa-linux"></span>
							<h3>Linux</h3>
							<p>Centos<br>Kail</p>
						</div>

						<div>
							<span class="icon fa-html5"></span>
							<h3>HTML+CSS+JAVASCRIPT</h3>
							<p>正在学习</p>
						</div>

						<div>
							<span class="icon fa-bug"></span>
							<h3>爬虫</h3>
							<p>业余爱好</p>
						</div>

					</div>

					<footer>
						<a href="{% url 'app:blog_index' %}" class="button">进入博客</a>
					</footer>
				</div>
			</section>


		<!-- Three -->
			<section id="three" class="wrapper align-center">
				<div class="inner">
					<div class="flex flex-2">
						<article>
							<div class="image round">
								<img src="../static/images/pic01.jpg" alt="Pic 01" />
							</div>
							<header>
								<h3>摄影<br />PHOTOGRAPYHY</h3>
							</header>
							<p>xxxxxxx<br />xxxxxxxxxxxxx</p>
							<footer>
								<a href="#" class="button">进入相册</a>
							</footer>
						</article>
						<article>
							<div class="image round">
								<img src="../static/images/pic02.jpg" alt="Pic 02" />
							</div>
							<header>
								<h3>涂鸦<br />GRAFFITI</h3>
							</header>
							<p>xxxxxxx<br />xxxxxxxxxxx</p>
							<footer>
								<a href="#" class="button">进入相册</a>
							</footer>
						</article>
					</div>
				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">

					<h3>联系我</h3>

{#					<form action="#" method="post">#}

						<div class="field half first">
							<label for="name">Name</label>
							<input name="name" id="name" type="text" placeholder="Name">
						</div>
						<div class="field half">
							<label for="email">Email</label>
							<input name="email" id="email" type="email" placeholder="Email">
						</div>
						<div class="field">
							<label for="message">Message</label>
							<textarea name="message" id="message" rows="6" placeholder="Message"></textarea>
						</div>
						<ul class="actions">
							<li><input value="Send Message" class="button alt" type="submit"></li>
						</ul>
{#					</form>#}


					

				</div>
			</footer>


		<!-- Scripts -->
			<script src="/static/js/jquery.min.js"></script>
			<script src="/static/js/skel.min.js"></script>
			<script src="/static/js/util.js"></script>
			<script src="/static/js/main.js"></script>

	</body>
</html>